server:
  port: 1650

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  data:
    mongodb:
      uri: ${DB_URI}

google-ios-client-id: ${GOOGLE_IOS_CLIENT_ID}
google-web-client-id: ${GOOGLE_WEB_CLIENT_ID}