server:
  port: ${PORT:1650}

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  data:
    mongodb:
      uri: ${DB_URI}

front-end-url: ${FRONT_END_URL}
google-ios-client-id: ${GOOGLE_IOS_CLIENT_ID}
google-web-client-id: ${GOOGLE_WEB_CLIENT_ID}